Revert "fix: Fix error 'address host value must be string'"
This reverts commit 9f99a41093c422774a6465e56d82737c0c68604d.

Commit caused an error when running script from shell::

```
$ sony-headphones-control xx:xx:xx:xx:xx:xx noise-cancelling

Searching for 04:5D:4B:EC:7C:0F...
Traceback (most recent call last):
  File "/usr/bin/sony-headphones-control", line 4, in <module>
    __import__('pkg_resources').run_script('SonyHeadphonesControl==0.1', 'sony-headphones-control')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.8/site-packages/SonyHeadphonesControl-0.1-py3.8.egg/EGG-INFO/scripts/sony-headphones-control", line 27, in <module>
    host = str(first_match["host"], 'utf-8')
TypeError: decoding str is not supported
```